- name: copy {{ component }} service
  ansible.builtin.template:
    src: "{{ component }}.service.j2"  #catalogue.service.j2 (templates)
    dest: "/etc/systemd/system/{{ component }}.service"
  notify: daemon reload

- name: start the service
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes
